export const leadershipContent = {
  title: "Leadership",
  content: [
    "Leadership approach:",
    "- Lead with clarity and ownership",
    "- Align on outcomes, reduce ambiguity, and create tight feedback loops",
    "",
    "Team leadership:",
    "- Align on outcomes and constraints (scope, quality, timelines)",
    "- Define ownership boundaries and decision-making paths",
    "- Unblock quickly by making trade-offs explicit and documented",
    "",
    "Mentorship:",
    "- Pair on critical work to build intuition, not just output",
    "- Teach systematic debugging and safe incremental changes",
    "- Make success repeatable via playbooks and shared primitives",
    "",
    "Code review philosophy:",
    "- Protect users and production first: correctness, security, performance",
    "- Prefer clear contracts, tests at boundaries, and minimal surface area",
    "- Use reviews to transfer context and raise the bar, not to gatekeep",
    "",
    "Ownership examples:",
    "- Driving refactors that simplify hot paths and reduce failure modes",
    "- Establishing conventions to prevent classes of bugs",
    "- Operational readiness: logs, metrics, alerts, runbooks",
  ].join("\n"),
} as const;

